name: build

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: build
      env:
        CGO_ENABLED: 0
        GOOS: linux
        GOARCH: amd64
      run: |
           go build -buildvcs=false -ldflags="-s -w" -o elect -v ./...
           tar czf elect.tar.gz elect

    - uses: softprops/action-gh-release@v2
      with:
        files: ${{ github.workspace }}/elect.tar.gz
